/**
 * Session worker environments driven by the `mcpJs` setting.
 *
 * Without the setting the worker runs on `NodeExecutionEnv` and bash. With
 * `mode: "standalone"` it embeds the mcp-js engine through generated native
 * bindings; with `mode: "coordinator"` it talks to an mcp-js HTTP server or
 * cluster. In both modes the pi session id is the engine session name, so the
 * session's heap and filesystem snapshot follow the pi session, and pi's own
 * session files stay on the host.
 */

import { existsSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { FileSystem } from "@earendil-works/pi-agent-core";
import {
	McpJsExecutionEnv,
	McpJsHttpEngine,
	type McpJsNativeEngine,
	NodeExecutionEnv,
} from "@earendil-works/pi-agent-core/node";
import { createJiti } from "jiti/static";
import { getAgentDir } from "../config.ts";
import { type McpJsSettings, SettingsManager } from "../core/settings-manager.ts";
import type { CreateSessionWorkerExecutionEnv, SessionWorkerEnvironments } from "./session-worker.ts";

/** Chainable builder as generated by mcp-js's UniFFI builder derive. */
interface Builder {
	build(): unknown;
}
interface ExecutionLimitsBuilder extends Builder {
	heapMemoryMaxMb(value: bigint): ExecutionLimitsBuilder;
	executionTimeoutSecs(value: bigint): ExecutionLimitsBuilder;
}
interface FilesystemAccessBuilder extends Builder {
	policiesJson(value: string): FilesystemAccessBuilder;
}
interface BlobStoreBuilder extends Builder {
	backend(value: unknown): BlobStoreBuilder;
}
interface WasmModuleFileBuilder extends Builder {
	name(value: string): WasmModuleFileBuilder;
	path(value: string): WasmModuleFileBuilder;
}
interface EngineConfigBuilder extends Builder {
	limits(value: unknown): EngineConfigBuilder;
	dataDir(value: string): EngineConfigBuilder;
	filesystem(value: unknown): EngineConfigBuilder;
	heapStore(value: unknown): EngineConfigBuilder;
	fsSnapshotStore(value: unknown): EngineConfigBuilder;
	wasmModules(value: unknown[]): EngineConfigBuilder;
}

/** The parts of the generated bindings module the standalone mode uses. */
export interface McpJsBindingsModule {
	Engine: { create(config: unknown): McpJsNativeEngine };
	EngineConfigBuilder: new () => EngineConfigBuilder;
	ExecutionLimitsBuilder: new () => ExecutionLimitsBuilder;
	FilesystemAccessBuilder: new () => FilesystemAccessBuilder;
	BlobStoreBuilder: new () => BlobStoreBuilder;
	WasmModuleFileBuilder: new () => WasmModuleFileBuilder;
	StoreBackend: { Directory: unknown };
}

export interface McpJsEnvironmentDependencies {
	/** Load the generated bindings module for standalone mode. Defaults to a jiti import. */
	loadBindings?: (path: string) => Promise<McpJsBindingsModule>;
	/** Connect to a server for coordinator mode. Defaults to {@link McpJsHttpEngine.connect}. */
	connect?: (url: string, headers: Record<string, string> | undefined) => Promise<McpJsNativeEngine>;
	/** Read the `mcpJs` setting for a working directory. Defaults to the settings manager. */
	readSettings?: (cwd: string) => McpJsSettings | undefined;
	/** Base directory for default paths such as `dataDir`. */
	agentDir?: string;
}

const DEFAULT_HEAP_MB = 256;
const DEFAULT_TIMEOUT_SECS = 60;
const DEFAULT_SNAPSHOT_CWD = "/work";

function isBindingsModule(value: unknown): value is McpJsBindingsModule {
	if (!value || typeof value !== "object") return false;
	const module = value as Record<string, unknown>;
	const engine = module.Engine as Record<string, unknown> | undefined;
	return (
		typeof engine?.create === "function" &&
		[
			"EngineConfigBuilder",
			"ExecutionLimitsBuilder",
			"FilesystemAccessBuilder",
			"BlobStoreBuilder",
			"WasmModuleFileBuilder",
		].every((name) => typeof module[name] === "function") &&
		typeof module.StoreBackend === "object"
	);
}

async function loadBindingsWithJiti(path: string): Promise<McpJsBindingsModule> {
	const jiti = createJiti(import.meta.url, { moduleCache: false });
	const module: unknown = await jiti.import(pathToFileURL(path).href);
	if (!isBindingsModule(module)) {
		throw new Error(`${path} does not export the mcp-js Engine and configuration builders`);
	}
	return module;
}

/** The `filesystem` policies JSON: a Rego file path becomes a one-policy chain. */
export function policiesJson(policy: string | undefined, agentDir: string): string {
	if (policy === undefined) {
		throw new Error("mcpJs.policy is required in standalone mode: a filesystem Rego policy path or policies JSON");
	}
	const trimmed = policy.trim();
	if (trimmed.startsWith("{")) return trimmed;
	const path = isAbsolute(trimmed) ? trimmed : resolve(agentDir, trimmed);
	if (!existsSync(path)) throw new Error(`mcpJs.policy not found: ${path}`);
	return JSON.stringify({ policies: [{ url: pathToFileURL(path).href }] });
}

function standaloneEngine(bindings: McpJsBindingsModule, settings: McpJsSettings, agentDir: string): McpJsNativeEngine {
	const limits = new bindings.ExecutionLimitsBuilder()
		.heapMemoryMaxMb(BigInt(settings.heapMemoryMaxMb ?? DEFAULT_HEAP_MB))
		.executionTimeoutSecs(BigInt(settings.executionTimeoutSecs ?? DEFAULT_TIMEOUT_SECS))
		.build();
	let config = new bindings.EngineConfigBuilder()
		.limits(limits)
		.dataDir(settings.dataDir ?? join(agentDir, "mcp-js"))
		.filesystem(new bindings.FilesystemAccessBuilder().policiesJson(policiesJson(settings.policy, agentDir)).build());
	const directory = () => new bindings.BlobStoreBuilder().backend(bindings.StoreBackend.Directory).build();
	const wasm = Object.entries(settings.wasmModules ?? {});
	if (settings.heap !== false && wasm.length === 0) config = config.heapStore(directory());
	if (settings.snapshots !== false) config = config.fsSnapshotStore(directory());
	if (wasm.length > 0) {
		config = config.wasmModules(
			wasm.map(([name, path]) => new bindings.WasmModuleFileBuilder().name(name).path(path).build()),
		);
	}
	return bindings.Engine.create(config.build());
}

/**
 * Build the session worker's environment factory. With no `mcpJs` setting the
 * worker keeps the Node shell environment.
 */
export function createMcpJsEnvironmentFactory(
	dependencies: McpJsEnvironmentDependencies = {},
): CreateSessionWorkerExecutionEnv {
	const readSettings = dependencies.readSettings ?? ((cwd) => SettingsManager.create(cwd).getMcpJs());
	const loadBindings = dependencies.loadBindings ?? loadBindingsWithJiti;
	const connect =
		dependencies.connect ??
		((url, headers) => McpJsHttpEngine.connect({ url, headers }) as Promise<McpJsNativeEngine>);
	return async (cwd, sessionId): Promise<SessionWorkerEnvironments | NodeExecutionEnv> => {
		const settings = readSettings(cwd);
		if (settings === undefined) return new NodeExecutionEnv({ cwd });
		const agentDir = dependencies.agentDir ?? getAgentDir();
		let engine: McpJsNativeEngine;
		if (settings.mode === "coordinator") {
			if (!settings.url) throw new Error("mcpJs.url is required in coordinator mode");
			engine = await connect(settings.url, settings.headers);
		} else if (settings.mode === "standalone") {
			if (!settings.bindings) throw new Error("mcpJs.bindings is required in standalone mode");
			const bindingsPath = isAbsolute(settings.bindings) ? settings.bindings : resolve(agentDir, settings.bindings);
			engine = standaloneEngine(await loadBindings(bindingsPath), settings, agentDir);
		} else {
			throw new Error(`mcpJs.mode must be "standalone" or "coordinator", not ${JSON.stringify(settings.mode)}`);
		}
		const files = settings.files ?? (engine.capabilities().filesystem ? "session" : "host");
		const snapshotCwd = files === "session" ? (settings.snapshotCwd ?? DEFAULT_SNAPSHOT_CWD) : cwd;
		const execution = new McpJsExecutionEnv(engine, snapshotCwd, { session: sessionId, files });
		const sessionStore: FileSystem = new NodeExecutionEnv({ cwd });
		return { execution, sessionStore };
	};
}
